UI, itemCube, TrashCan 추가
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-21 pull request #105
Opened 2024-12-03 17:34 UTC by charliennnsdk

# PR Title 메인화면 GUI 생성, 기타 GUI 작업, itemCube 모델링, TrashCan 모델링추가

## PR Description
메인화면 GUI를 생성하였습니다.
기타 GUI 작업 진행중입니다. (추가 수정 예정)
itemCube 모델링을 추가하였습니다. (prefab에 크기 0.2로 설정된 모델링 추가 완료)
TrashCan 모델링을 추가했습니다 (Asset / Models)

### Screenshots (if UI changes were made)
<img width="1043" alt="스크린샷 2024-12-04 오전 2 26 19" src="https://github.com/user-attachments/assets/add80def-7c2f-48c6-a861-b46fc71e656f">
아이템 큐브 스크린샷입니다.
## Reviewer Checklist
-GUI TestCase에서 일괄 테스트 예정

2024-12-03 23:48 UTC, Boseong-Seo approved these changes

2024-12-04 03:01 UTC, tpwls6630 commented on Computer Virus Survivors/Assets/Scripts/Player/PlayerController.cs
플레이어 컨트롤러 무기 수정은 취소해주세요

2024-12-04 03:05 UTC, Nyso97 requested changes
MainScene의 UI가 화면 비율 설정에 따라 변합니다. Canvas Scaler의 UI Scale Mode를 Scale with Screen Size로 해주셔야 할 것 같습니다.
그리고 지금 merge conflict가 있어서 이것도 해결해야 할 것 같습니다.

2024-12-04 09:29 UTC, charliennnsdk commented on Computer Virus Survivors/Assets/Scripts/Player/PlayerController.cs
해당 사항 적용하였습니다

2024-12-04 09:43 UTC, charliennnsdk commented
merge conflict는 추가 확인해보겠습니다

2024-12-04 09:49 UTC, closed without merging