Trash Can, Item cube 모델 추가
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-21 pull request #124
Opened 2024-12-07 06:50 UTC by charliennnsdk

merge conflict 해결 테스트 커밋입니다.

# PR Title [Trash Can, Item Cube 모델 추가]
## Related Issue(s)
모델 자체 추가 보다는, Merge Conflict 관련 확인이 필요합니다.

## Reviewer Checklist
- [ ] Merge Conflict
---

2024-12-07 08:45 UTC, Nyso97 requested changes
Conflict는 안나는데 단조 font 부분이 뭔가 이상합니다
기존 ㄷㅏㄴㅈㅗ.meta 파일이 있었는데 단조.meta 파일이 새로 추가되고 있는 것 같습니다. 라이선스.txt도 그렇고요
원래 파일이 문제인거 같긴 한데 일단 font만 빼고 PR해주시면 좋을 것 같습니다.

2024-12-07 08:46 UTC, charliennnsdk commented
아마 맥 문제인것같습니다. 해당 부분 제외하고 pr하겠습니다!

2024-12-07 09:03 UTC, Nyso97 commented
![Computer Virus Survivors - MainScene - Windows, Mac, Linux - Unity 2021 3 42f1 Personal _DX11_ 2024-12-07 오후 5_58_04](https://github.com/user-attachments/assets/59bc5d0f-e519-462a-9b15-156edeeaefe6)

마우스 움직임 따라서 UI 움직이게 하는게 약간 과할 때가 있습니다.
이전 마우스 위치 말고 화면 중앙 기준으로 움직이게 하는게 어떨까 싶습니다.

2024-12-07 09:06 UTC, charliennnsdk commented
<img width="421" alt="image" src="https://github.com/user-attachments/assets/daf5a5f7-fd11-44a5-af3d-8692efdfaa8f">
움직이는 각 컴포넌트에 "Sensitivity" 가 현재 0.05(타이틀) / 0.025(버튼) 로 지정되어있는데, 해당 부분 수정하면 될 것 같습니다. (0.025/0.0125)

2024-12-07 09:18 UTC, Nyso97 commented
그런데 일단 제가 느끼기에는 화면 중앙을 기준으로 해서 움직이는 게 좀 더 직관적인 것 같습니다.

2024-12-07 09:57 UTC, charliennnsdk commented
화면 중앙...이라는 개념이 잘 이해가 안가는데 혹시 중심점을 화면 가운데로 잡는게 맞을까요?

2024-12-07 10:00 UTC, Nyso97 commented
> 화면 중앙...이라는 개념이 잘 이해가 안가는데 혹시 중심점을 화면 가운데로 잡는게 맞을까요?

네네 맞습니다
screenCenter = new Vector3(Screen.width / 2, Screen.height / 2, 0);
이런 식으로 하면 될거에요

2024-12-07 10:03 UTC, charliennnsdk commented
넵! 적용해서 커밋하겠습니다

2024-12-07 10:17 UTC, Nyso97 commented
버튼 쪽에 문제가 있는 것 같습니다.
제가 해봤는데 버튼에 달려 있는 UIFollowMouse 다 제거하고 버튼 그룹을 Title에다가 옮겨주면 잘 작동하는 것 같습니다.

2024-12-07 10:19 UTC, charliennnsdk commented
넵 확인하여 변경 커밋하였습니다.

2024-12-09 04:45 UTC, tpwls6630 commented
제가 확인 했을 땐 문제 없어보였습니다

2024-12-09 06:08 UTC, Nyso97 approved these changes
다른 거 할게 많아서 review가 늦었네요...

2024-12-09 06:08 UTC, merged