중간보스 animation 추가
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-21 pull request #129
Opened 2024-12-11 17:56 UTC by Boseong-Seo

# 중간보스 애니메이션 추가
## PR Description
- 트로이목마 모델링도 약간 수정함
- 애니메이션 추가 ; 전진하면서 대쉬공격 (?)
  + 회의 때 피드백 고려해서 좀 더 앞발을 드는 방식으로 수정함.
- Virus_Trojan_Anim 이라는 이름으로 prefab 저장

### Screenshots (if UI changes were made)
애니메이션 동작은 아래와 같이 합니다.

https://github.com/user-attachments/assets/c74a9a8c-a9c8-408a-ac9d-28a92765085d

2024-12-12 09:24 UTC, Nyso97 requested changes
.

2024-12-12 14:19 UTC, Boseong-Seo commented
> 앞발 들기랑 대쉬 사이에 잠깐 딜레이를 추가해주실 수 있을까요? 유니티 내에서 그 딜레이 시간을 조절할 수 있으면 더 좋고요

네네 수정해서 커밋 올려보겠습니다.
가능하면 유니티에서 시간을 조절할 수 있는 방법으로 알아볼게요.

2024-12-13 07:17 UTC, Boseong-Seo commented
기존에 하나로 되어 있던 애니메이션을
앞발 드는 애니메이션(FrontLegMotion) + 전진 애니메이션 (Forward) 나눠서
두 state 간에 transition을 넣는 방식으로 딜레이 넣었구요. (아래 예시 영상 참고)
https://github.com/user-attachments/assets/49ae38d2-3917-44b5-b79c-b7324549e97a

---

![Frame 2](https://github.com/user-attachments/assets/02d685a6-cb56-498e-bbc7-1b3e07767843)

"Trojan" animator에서 state 간 transition 화살표 클릭하면 inspector 창에서
위 사진과 같이 transition(빨간색 네모 부분)을 조절할 수 있게 되는데
- 동그라미 친 저, 두 애니메이션 간 겹치는 시작 부분을 0:20 ~ 0:25 사이로 조절하시거나
- `transition duration` 값(=두 애니메이션을 얼마동안 겹쳐둘 것인지)을 조절하시는 식으로 딜레이 정도를 원하시는 대로 조절하실 수 있을 거예요.
- `transition offset`(=두 번째 애니메이션의 어느 부분부터 연결시킬 것인지)은 0으로 계속 둬주시면 될 것 같습니다.

2024-12-13 13:08 UTC, Nyso97 commented
혹시 Forward의 돌진하는 길이도 조정이 가능한가요?

2024-12-14 03:09 UTC, Boseong-Seo commented
움직이는 길이 자체를 유니티에서 수정하는 방법은 없는 것 같아서 ㅜ
약간 편법(?)을 써서 Forward 애니메이션 길이를 잘라서 사용하는 방식으로 해볼 순 있을 것 같아요.

----
아래와 같은 방식으로 Forward 애니메이션 클립의 길이를 조절해서 사용하시면 될 것 같아요.
End 값을 [12, ~) range 내에서 원하시는 대로 조절하시면 됩니다.
(지금은 프레임 길이가 18초로 들어가 있고, Forward 애니메이션 속도도 0.8로 들어가 있어요. 원하시는 대로 조절해서 사용하시면 될 것 같습니다.)

![Frame 3](https://github.com/user-attachments/assets/55ee73c2-5352-4a96-9dde-eb6d6317841f)

2024-12-14 03:10 UTC, Boseong-Seo commented
- Forward 길이를 12로 했을 때

https://github.com/user-attachments/assets/ec9aee80-dda2-4320-a4ae-8f7be4cf9c61



- Forward 길이를 18로 했을 때


https://github.com/user-attachments/assets/30362fea-5da7-4fe7-99b7-08c22da57be8

2024-12-14 05:20 UTC, Nyso97 commented
저 왜 적용이 안될까요...

https://github.com/user-attachments/assets/498e0e3a-cb19-45a8-bf0e-e310cbb58ca0

2024-12-14 05:49 UTC, Boseong-Seo commented
앗 그렇게 수정하신 다음에 Apply 버튼 까지 눌러주셔야 해요 !
그것까지 말씀드린다는 걸 깜박했네요 ㅜㅜ

2024-12-14 05:51 UTC, Nyso97 approved these changes
확인했습니다!

2024-12-14 05:51 UTC, merged