바이러스_칩_강화판/열화판 구분
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-21 pull request #133
Opened 2024-12-13 08:19 UTC by charliennnsdk

# PR Title [바이러스 칩 강화판/열화판 구분]

### Changes Included
- [ ] 열화판을 Lv01 (파란색), 강화판을 Lv02 (빨간색)으로 설정하여 구분하였습니다.

### Screenshots (if UI changes were made)
![image](https://github.com/user-attachments/assets/e067afe7-69f3-4068-8cd6-528d7535e355)

## Reviewer Checklist
- [ ] 크기가 적절한지
- [ ] 애니메이션이 적절한지

2024-12-13 13:14 UTC, Nyso97 commented
UI 소폭 수정은 뭐가 바뀐건가요?

2024-12-13 13:16 UTC, charliennnsdk commented
@Nyso97 MainScene에서 START버튼 글씨체 통일, 사망/성공 캔버스에서 stat, info 탭에 마우스 움직임 낮은 감도로 적용하였습니다.

2024-12-13 13:29 UTC, charliennnsdk commented
<img width="297" alt="image" src="https://github.com/user-attachments/assets/9cb3966e-2fea-44e9-a002-999c47c84f04" />
해당 버튼 수정전 사진이 저한테 없긴 한데, 해당 부분 이전 버전 보시면 글씨체가 다른 UI랑 다릅니다. 스탯,인포 패널은 수정해서 다시 올리겠습니다

2024-12-13 13:30 UTC, Nyso97 commented
> <img alt="image" width="297" src="https://private-user-images.githubusercontent.com/23337246/395575685-9cb3966e-2fea-44e9-a002-999c47c84f04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwOTY4NDYsIm5iZiI6MTczNDA5NjU0NiwicGF0aCI6Ii8yMzMzNzI0Ni8zOTU1NzU2ODUtOWNiMzk2NmUtMmZlYS00NGU5LWEwMDItOTk5YzQ3Yzg0ZjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDEzMjkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZWI4NWVkNGNjNmNjZWE4NDY2MzY0YjM5OTRhZGIxMmIyODNmOTNlZjMwMzAwMzdmZTdkNjRmM2UzMmNjZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.skYv2hURG05zuIyDbGgizn92E4wWftoi8WDg56T5sYA"> 해당 버튼 수정전 사진이 저한테 없긴 한데, 해당 부분 이전 버전 보시면 글씨체가 다른 UI랑 다릅니다. 스탯,인포 패널은 수정해서 다시 올리겠습니다

아 그러네요. start 버튼이 어딨는지를 못찾고 있었습니다 ㅋㅋ...

2024-12-13 13:42 UTC, Nyso97 requested changes
이거 몸체 검은색을 살짝만 밝게 해주실 수 있을까요?

2024-12-13 13:46 UTC, charliennnsdk commented
<img width="527" alt="image" src="https://github.com/user-attachments/assets/eff5ad80-c51f-42d8-8228-0ab67a9cd5f4" />
이정도 색이면 괜찮을까요?

2024-12-13 13:48 UTC, Nyso97 commented
밝으니까 덜 멋있어 보이는 것 같기도 하고.... 어려운데요;;
저 둘의 중간 색은 어떨까요

2024-12-13 13:56 UTC, charliennnsdk commented
@Nyso97 
<img width="575" alt="image" src="https://github.com/user-attachments/assets/b690ab3a-bbc0-4308-9c63-4865a491e77d" />
중간정도면 이정도 될 것 같습니다!

2024-12-13 14:01 UTC, Nyso97 commented
고민되네요... 그냥 수정 전 후 버전 다 넣어서 커밋해주실 수 있나요? 게임에 넣어서 직접 확인해볼려고요

2024-12-14 04:38 UTC, charliennnsdk commented
넵! 우선, Lv01 기준으로 프리팹 3가지 만들어서 커밋했습니다. 이 중에서 가장 낫다고 판단되시는 버전 알려주시면, 해당 버전에 맞춰서 Lv02도 적용하겠습니다!
![Uploading 스크린샷 2024-12-14 오후 1.35.00.png…]()

@Nyso97

2024-12-14 04:52 UTC, Nyso97 approved these changes
감사합니다!!

2024-12-14 04:52 UTC, merged